export const userRequest = [
    {
        id: "1",
        Investor: "Mayowa Sanusi",
        BusinessName: "Facebook",
        Amount: "$15,000",
        DateOfRequest: "03/10/2024",
        StatusImage: "/images/Approved.png",
    },
    {
        id: "2",
        Investor: "Boss Marvellous",
        BusinessName: "Vehance",
        Amount: "$15,000",
        DateOfRequest: "03/10/2024",
        StatusImage: "/images/pending.png",
    },
    {
        id: "3",
        Investor: "Wisdom Dakoh",
        BusinessName: "Stemlab",
        Amount: "$15,000",
        DateOfRequest: "03/10/2024",
        StatusImage: "/images/pending.png",
    },
    {
        id: "4",
        Investor: "Yusuf Momodu",
        BusinessName: "officeHub",
        Amount: "$15,000",
        DateOfRequest: "03/10/2024",
        StatusImage: "/images/Approved.png",
    },
    {
        id: "5",
        Investor: "Dauda Abdulshakur",
        BusinessName: "Amazon",
        Amount: "$15,000",
        DateOfRequest: "03/10/2024",
        StatusImage: "/images/pending.png",
    },
    {
        id: "6",
        Investor: "Mayowa Sanusi",
        BusinessName: "Facebook",
        Amount: "$15,000",
        DateOfRequest: "03/10/2024",
        StatusImage: "/images/Approved.png",
    },
    {
        id: "7",
        Investor: "Boss Marvellous",
        BusinessName: "Vehance",
        Amount: "$15,000",
        DateOfRequest: "03/10/2024",
        StatusImage: "/images/pending.png",
    },
    {
        id: "8",
        Investor: "Mayowa Sanusi",
        BusinessName: "Facebook",
        Amount: "$15,000",
        DateOfRequest: "03/10/2024",
        StatusImage: "/images/Approved.png",
    },
    {
        id: "9",
        Investor: "Boss Marvellous",
        BusinessName: "Vehance",
        Amount: "$15,000",
        DateOfRequest: "03/10/2024",
        StatusImage: "/images/pending.png",
    },
    {
        id: "10",
        Investor: "Mayowa Sanusi",
        BusinessName: "Facebook",
        Amount: "$15,000",
        DateOfRequest: "03/10/2024",
        StatusImage: "/images/Approved.png",
    },
    {
        id: "11",
        Investor: "Boss Marvellous",
        BusinessName: "Vehance",
        Amount: "$15,000",
        DateOfRequest: "03/10/2024",
        StatusImage: "/images/pending.png",
    },
    {
        id: "12",
        Investor: "Mayowa Sanusi",
        BusinessName: "Facebook",
        Amount: "$25,000",
        DateOfRequest: "03/10/2024",
        StatusImage: "/images/Approved.png",
    },
    {
        id: "13",
        Investor: "Boss Marvellous",
        BusinessName: "Vehance",
        Amount: "$35,000",
        DateOfRequest: "03/10/2024",
        StatusImage: "/images/pending.png",
    },
    {
        id: "14",
        Investor: "Mayowa Sanusi",
        BusinessName: "Facebook",
        Amount: "$45,000",
        DateOfRequest: "03/10/2024",
        StatusImage: "/images/Approved.png",
    },
    {
        id: "15",
        Investor: "Boss Marvellous",
        BusinessName: "Vehance",
        Amount: "$55,000",
        DateOfRequest: "03/10/2024",
        StatusImage: "/images/pending.png",
    },
    {
        id: "14",
        Investor: "Muhammad Abdul",
        BusinessName: "Facebook",
        Amount: "$45,000",
        DateOfRequest: "03/10/2024",
        StatusImage: "/images/Approved.png",
    },
    {
        id: "15",
        Investor: "Khadija Musa",
        BusinessName: "Vehance",
        Amount: "$55,000",
        DateOfRequest: "03/10/2024",
        StatusImage: "/images/pending.png",
    },
];

export const Investment = [{
        id: "1",
        BusinessName: "Vehance",
        Amount: "$55,000",
        ExpectedRoi: "10%",
        DateOfRequest: "03/10/2024",
        StatusImage: "/images/pending.png", 
},
{
    id: "2",
    BusinessName: "Solar",
    Amount: "$55,000",
    ExpectedRoi: "10%",
    DateOfRequest: "03/10/2024",
    StatusImage: "/images/pending.png", 
},
{
    id: "3",
    BusinessName: "Facebook",
    Amount: "$45,000",
    ExpectedRoi: "5%",
    DateOfRequest: "03/10/2024",
    StatusImage: "/images/Approved.png",
},
{
    id: "4",
    BusinessName: "Vehance",
    Amount: "$55,000",
    ExpectedRoi: "10%",
    DateOfRequest: "03/10/2024",
    StatusImage: "/images/pending.png", 
},
{
id: "5",
BusinessName: "Solar",
Amount: "$55,000",
ExpectedRoi: "10%",
DateOfRequest: "03/10/2024",
StatusImage: "/images/pending.png", 
},
{
id: "6",
BusinessName: "Geregu",
Amount: "$45,000",
ExpectedRoi: "5%",
DateOfRequest: "03/10/2024",
StatusImage: "/images/Approved.png",
},
{
    id: "7",
    BusinessName: "Oando PLC",
    Amount: "$85,000",
    ExpectedRoi: "19%",
    DateOfRequest: "03/12/2024",
    StatusImage: "/images/Failedtext.png",
    },
{
    id: "7",
    BusinessName: "Vehance",
    Amount: "$55,000",
    ExpectedRoi: "10%",
    DateOfRequest: "03/10/2024",
    StatusImage: "/images/pending.png", 
},
{
id: "8",
BusinessName: "MTN",
Amount: "$25,000",
ExpectedRoi: "30%",
DateOfRequest: "03/10/2024",
StatusImage: "/images/pending.png", 
},
{
id: "9",
BusinessName: "Youtube",
Amount: "$45,000",
ExpectedRoi: "25%",
DateOfRequest: "03/10/2024",
StatusImage: "/images/Approved.png",
},
]